services:
  xxxbot:
    image: nanssye/xxxbot:latest
    container_name: XXXBot
    restart: unless-stopped
    ports:
      - "9090:9090" # 管理后台端口
      - "3000:3000" # WeTTy终端端口
    volumes:
      - xxxbot:/app
      - redis_data:/var/lib/redis
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123

volumes:
  redis_data:
    name: redis_data
  xxxbot:
    name: XXXBot
